### ISSUE TITLE
mark.js overlaps

### ISSUE THREAD

**Issue by skurzinz** [KONDE-AT/dsebaseapp#18]
if searchexpr=something matches something that contains a tei:note, the resulting html is garbled. 

Example: https://mrp.oeaw.ac.at/pages/show.html?document=MRP-3-0-01-0-00000000-einleitung.xml&directory=editions&searchexpr=1848

**Comment by csae8092** [comment]
mentioned app does not use mark.js but https://mburakerman.github.io/hrjs/
mark.js was introduced to avoid things like mentioned above
