### ISSUE TITLE
Correct vertical positioning

### ISSUE THREAD

**Issue by skurzinz** [KONDE-AT/dsebaseapp#9]
In general, links within one page create an offset on clicking: 
Click on a footnote link and you land a few lines too high up. 
Backlinks from footnote to #fna_XXX are even worse. Looks like the top nav is not counted in positoining.

**Comment by skurzinz** [comment]
Just checked, this is not only a https://github.com/skurzinz/mrptestapp/ problem, but also present in RITA, e.g. https://rita.acdh.oeaw.ac.at/pages/show.html?document=1752-10-11.xml&directory=editions#fn8

**Comment by skurzinz** [comment]
This is similar to https://stackoverflow.com/questions/13555709/how-do-i-offset-where-my-fixed-nav-bar-takes-me

**Comment by skurzinz** [comment]
Solved for links to divs in https://github.com/skurzinz/mrptestapp/commit/8d6aac6bd623d3007ab40344b3f924fdeb717873. 
Still open when it comes to inline anchors as in footnote backreferences.

**Comment by skurzinz** [comment]
question of padding in nav. some switch to a non fixed-top nav.

**Comment by csae8092** [comment]
same issue here https://github.com/KONDE-AT/thun/issues/1
